version: 2.1
orbs:
  python: circleci/python@2.0.3
  node: circleci/node@5.0.3
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            export ELODIE_DIR=${PWD}
            pip install -r elodie/tests/requirements.txt
            pip install -r elodie/plugins/googlephotos/requirements.txt
            pip install coveralls
            sed -i.bak 's/debug = False/debug = True/g' elodie/constants.py
            wget https://exiftool.org/Image-ExifTool-12.50.tar.gz
            gzip -dc Image-ExifTool-12.50.tar.gz  | tar -xf -
            cd Image-ExifTool-12.50
            perl Makefile.PL
            sudo make install
            echo "which exiftool command"
            which exiftool
            cd ${ELODIE_DIR}
            ./elodie/tests/run_tests.py -w elodie/tests --with-coverage --cover-package=elodie
      - coveralls/upload
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
