version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            export ELODIE_DIR=${PWD}
            pip install -r elodie/tests/requirements.txt
            pip install -r elodie/plugins/googlephotos/requirements.txt
            pip install coveralls
            mkdir ${ELODIE_DIR}/.elodie
            ls
            sed "s/your-api-key-goes-here/x8wQLqGhW7qK3sFpjYtVTogVtoMK0S8s/g" config.ini-sample > .elodie/config.ini
            sed -i.bak 's/debug = False/debug = True/g' elodie/constants.py
            wget https://exiftool.org/Image-ExifTool-12.50.tar.gz
            gzip -dc Image-ExifTool-12.50.tar.gz  | tar -xf -
            cd Image-ExifTool-12.50
            perl Makefile.PL
            sudo make install
            cd ${ELODIE_DIR}
            ./elodie/tests/run_tests.py -w elodie/tests --with-coverage --cover-package=elodie
            coveralls
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
