CREATE TABLE "metadata" (
	"id"	INTEGER,
	"appId"	TEXT,
	"url"	TEXT,
	"host"	TEXT,
	"title"	TEXT,
	"description"	TEXT,
	"key"	TEXT,
	"hash"	TEXT,
	"tags"	TEXT,
	"size"	INTEGER,
	"width"	INTEGER,
	"height"	INTEGER,
	"rotation"	INTEGER,
	"exifOrientation"	INTEGER,
	"exifCameraMake"	TEXT,
	"exifExposureTime"	TEXT,
	"exifFNumber"	TEXT,
	"exifMaxApertureValue"	TEXT,
	"exifMeteringMode"	TEXT,
	"exifFlash"	TEXT,
	"exifFocalLength"	TEXT,
	"altitude"	INTEGER,
	"latitude"	REAL,
	"longitude"	REAL,
	"views"	INTEGER,
	"status"	INTEGER,
	"permission"	INTEGER,
	"groups"	TEXT,
	"license"	TEXT,
	"dateTaken"	INTEGER,
	"dateTakenDay"	INTEGER,
	"dateTakenMonth"	INTEGER,
	"dateTakenYear"	INTEGER,
	"dateUploaded"	INTEGER,
	"dateUploadedDay"	INTEGER,
	"dateUploadedMonth"	INTEGER,
	"dateUploadedYear"	INTEGER,
	"pathOriginal"	TEXT,
	"pathBase"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE UNIQUE INDEX "pathOriginal" ON "metadata" (
	"pathOriginal"
);
